//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilmDirectorDetail
    {
        public int FilmDirectorDetailID { get; set; }
        public int FilmId { get; set; }
        public int DirectorId { get; set; }
        public Nullable<int> DirectorRate { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual Film Film { get; set; }
    }
}
