//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Film()
        {
            this.FilmActorDetail = new HashSet<FilmActorDetail>();
            this.FilmCategoryDetail = new HashSet<FilmCategoryDetail>();
            this.FilmCustomerDetail = new HashSet<FilmCustomerDetail>();
            this.FilmDirectorDetail = new HashSet<FilmDirectorDetail>();
        }
    
        public int FilmId { get; set; }
        public string FilmName { get; set; }
        public int Views { get; set; }
        public Nullable<int> Vote { get; set; }
        public decimal FilmDuration { get; set; }
        public Nullable<System.DateTime> DateOfConstruction { get; set; }
        public string Language { get; set; }
        public Nullable<decimal> FilmEndorsement { get; set; }
        public bool Status { get; set; }
        public string images { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmActorDetail> FilmActorDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmCategoryDetail> FilmCategoryDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmCustomerDetail> FilmCustomerDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FilmDirectorDetail> FilmDirectorDetail { get; set; }
    }
}
