//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FilmBox_DbEntities1 : DbContext
    {
        public FilmBox_DbEntities1()
            : base("name=FilmBox_DbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Actor> Actor { get; set; }
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Director> Director { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<FilmActorDetail> FilmActorDetail { get; set; }
        public virtual DbSet<FilmCategoryDetail> FilmCategoryDetail { get; set; }
        public virtual DbSet<FilmCustomerDetail> FilmCustomerDetail { get; set; }
        public virtual DbSet<FilmDirectorDetail> FilmDirectorDetail { get; set; }
        public virtual DbSet<Series> Series { get; set; }
        public virtual DbSet<SeriesActorDetail> SeriesActorDetail { get; set; }
        public virtual DbSet<SeriesCategoryDetail> SeriesCategoryDetail { get; set; }
        public virtual DbSet<SeriesCustomerDetail> SeriesCustomerDetail { get; set; }
        public virtual DbSet<SeriesDirectorDetail> SeriesDirectorDetail { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
